title: Adınız Soyadınız
description: Academic Research Library
theme: jekyll-theme-minimal   # GitHub Pages’in yerleşik "Minimal" teması
logo: /assets/avatar.jpg      # (isteğe bağlı)
google_scholar: https://scholar.google.com/citations?user=XXXX
linkedin: https://www.linkedin.com/in/xxxx
twitter: https://x.com/xxxx
